apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-future-base-service-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: node-future-base-service
    spec:
      containers:
      - name: node-future-base-service
        image: daocloud.io/baidao/node-future-base-service:20170616171322
        resources:
          limits:
            cpu: 800m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: k8s
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone-volume
          readOnly: true
      volumes:
      - name: timezone-volume
        hostPath:
          path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-future-base-service   
  name: node-future-base-service-svc         
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-future-base-service
  type: ClusterIP